### ISSUE TITLE
mesh_generator

### ISSUE THREAD

**Issue by WangJun-ZJUT** [wenbingtao/SSRNet#2]
您好！非常感谢您的工作，我们在复现项目时发现缺少mesh_generator所需的代码的，请问方便提供一下吗？

**Comment by KKScofield** [comment]
> 您好！非常感谢您的工作，我们在复现项目时发现缺少mesh_generator所需的代码的，请问方便提供一下吗？

请问您找到mesh_generator的代码了吗？活着有别的办法复现吗？
